port: /dev/ttyUSB0
read_rate: 50
write_rate: 25
joints: {
    joint_1: {id: 1, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false },
    joint_2: {id: 2, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false},
    joint_3: {id: 3, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false},
    joint_4: {id: 4, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false},
    joint_5: {id: 5, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false},
    joint_6: {id: 6, ticks: 4096, range: 360.0, max_speed: 100.0, invert: false},
}
controllers: {
    harness_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4, joint_5,joint_6]},
}